#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
#
# CERN Search is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

set -e

readonly SCRIPT_PATH=$(dirname "$0")
readonly TLS_DIR="$SCRIPT_PATH/../../nginx/tls"

export FLASK_ENV=development

# Start Server
invenio run \
       --cert "$TLS_DIR/tls.crt" \
       --key "$TLS_DIR/tls.key" & pid_server=$!

trap 'kill $pid_server &>/dev/null' EXIT

wait $pid_server
